[package]
name = "sessionevent-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1"
syn = "2"
proc-macro2 = "1"
darling = "0.20"
eventdata = {path="../eventdata"}